### ISSUE TITLE
Vision?

### ISSUE THREAD

**Issue by mxstbr** [jxnblk/react-server#1]
Why should I use `react-server` over Razzle or after.js or even Next.js?

**Comment by jaredpalmer** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/d331eb63-425c-4592-9674-819f29263516-acc85966-59c8-450c-aa31-6f6ec4b82556-v1.png?transparent=1&palette=1&width=246)

**Comment by mxstbr** [comment]
Oh shit if @jaredpalmer says it's lit I guess we gotta go and rewrite Spectrum in it! 😜

**Comment by jaredpalmer** [comment]
actually @mxstbr you may be rewriting with razzle as i'm planning to add modes in next version for `client`, `server`, `iso`, `static`

**Comment by mxstbr** [comment]
Okay okay okay, but let me suggest a deal that benefits both of us: you rewrite Spectrum in razzle and I'll ship it. You get to say we built it with razzle and test all the new features you're building, we get to use razzle and don't have to mess around with our SSR crap anymore. Deal?

**Comment by jxnblk** [comment]
You should **absolutely use razzle**, this was for two purposes:

1. To help me understand how razzle actually does the HMR on server and client
2. To share that clever setup with other people minus the other things that Razzle does

But keep an eye out for a `jxn-scripts` package at some point ;)

**Comment by jxnblk** [comment]
Also Next.js is really, really great
